// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleMiddleware.Data;

namespace SampleMiddleware.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20181127093333_TambahFieldAddressTableRestaurant")]
    partial class TambahFieldAddressTableRestaurant
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SampleMiddleware.Models.Jenis", b =>
                {
                    b.Property<int>("JenisID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NamaJenis");

                    b.HasKey("JenisID");

                    b.ToTable("Jenis");
                });

            modelBuilder.Entity("SampleMiddleware.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int?>("JenisID");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("JenisID");

                    b.ToTable("Restaurant");
                });

            modelBuilder.Entity("SampleMiddleware.Models.Restaurant", b =>
                {
                    b.HasOne("SampleMiddleware.Models.Jenis", "Jenis")
                        .WithMany("Restaurants")
                        .HasForeignKey("JenisID");
                });
#pragma warning restore 612, 618
        }
    }
}
